### ISSUE TITLE
keyframes_extract_diff 运行错误

### ISSUE THREAD

**Issue by dcboy** [monkeyDemon/AI-Toolbox#3]
```
➜  keyframes_extract_tool python keyframes_extract_diff.py
/usr/bin/python
target video :pikachu.mp4
frame save directory: ./extract_result/
Using Local Maxima
1923 50
Traceback (most recent call last):
  File "keyframes_extract_diff.py", line 195, in <module>
    plt.locator_params(numticks=100)
  File "/home/yopoint/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2744, in locator_params
    return gca().locator_params(axis=axis, tight=tight, **kwargs)
  File "/home/yopoint/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3006, in locator_params
    self.xaxis.get_major_locator().set_params(**kwargs)
  File "/home/yopoint/.local/lib/python3.6/site-packages/matplotlib/ticker.py", line 2212, in set_params
    f"set_params() got an unexpected keyword argument '{key}'")
TypeError: set_params() got an unexpected keyword argument 'numticks'
➜  keyframes_extract_tool
```

**Comment by CharliePip** [comment]
有一处改成：
plt.locator_params(axis='both', nbins=10)
就行了

**Comment by iannluca** [comment]
你好，我运行Keyframe_extract_fiff出现问题，你能帮我解决下吗
Using Local Maxima
0 10
Traceback (most recent call last):
  File "c:/Users/asus/Desktop/新建文件夹 (3)/keyframe.py", line 182, in <module>
    sm_diff_array = smooth(diff_array, len_window)
  File "c:/Users/asus/Desktop/新建文件夹 (3)/keyframe.py", line 79, in smooth
    s = np.r_[2 * x[0] - x[window_len:1:-1],
IndexError: index 0 is out of bounds for axis 0 with size 0
